GET http://localhost:4000/

###

POST http://localhost:4000/api/shop/categories/new
Content-Type: application/json

{
    "title":"Jacket"
}

### get all categories

GET http://localhost:4000/api/shop/categories

### add new item
POST http://localhost:4000/api/shop/items/new
Content-Type: application/json

{
    "title":"green hat"
}