GET http://localhost:4000/

###

POST http://localhost:4000/api/shop/categories/new
Content-Type: application/json

{
    "title":"Jacket"
}

### get all categories

GET http://localhost:4000/api/shop/categories

### add new item
POST http://localhost:4000/api/shop/items/new
Content-Type: application/json

{
    "title":"green hat"
}

### Get all items

GET http://localhost:4000/api/shop/items

### Get  single item 
GET http://localhost:4000/api/shop/items/60e6985bbfd94d97e014da26


### add new user

POST http://localhost:4000/api/user/new
Content-Type: application/json

{
    "name":"new name"
}

### Get all users

GET http://localhost:4000/api/users

### Get  single user
GET http://localhost:4000/api/users/60e6d62982e923a86848d0db


### CART =============================






GET http://localhost:4000/api/shop/cart/asfdaf

### add item to cart

POST http://localhost:4000/api/shop/cart/1234
Content-Type: application/json

{
    
        "ShopItem": "afdsafdsafds"
    
}

### PUT request to cart
PUT http://localhost:4000/api/shop/cart/1234